/*
 * generated by Xtext 2.9.0.v201505220408
 */
package me.tomassetti.serializer;

import com.google.inject.Inject;
import java.util.List;
import me.tomassetti.services.AstTransformationsDslGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class AstTransformationsDslSyntacticSequencer extends AbstractSyntacticSequencer {

	protected AstTransformationsDslGrammarAccess grammarAccess;
	protected AbstractElementAlias match_AttributeNodeTypeField_BooleanKeyword_1_2_or_IntKeyword_1_1_or_StringKeyword_1_0;
	protected AbstractElementAlias match_NodeType_AbstractKeyword_0_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (AstTransformationsDslGrammarAccess) access;
		match_AttributeNodeTypeField_BooleanKeyword_1_2_or_IntKeyword_1_1_or_StringKeyword_1_0 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getAttributeNodeTypeFieldAccess().getBooleanKeyword_1_2()), new TokenAlias(false, false, grammarAccess.getAttributeNodeTypeFieldAccess().getIntKeyword_1_1()), new TokenAlias(false, false, grammarAccess.getAttributeNodeTypeFieldAccess().getStringKeyword_1_0()));
		match_NodeType_AbstractKeyword_0_q = new TokenAlias(false, true, grammarAccess.getNodeTypeAccess().getAbstractKeyword_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if(match_AttributeNodeTypeField_BooleanKeyword_1_2_or_IntKeyword_1_1_or_StringKeyword_1_0.equals(syntax))
				emit_AttributeNodeTypeField_BooleanKeyword_1_2_or_IntKeyword_1_1_or_StringKeyword_1_0(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_NodeType_AbstractKeyword_0_q.equals(syntax))
				emit_NodeType_AbstractKeyword_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     'string' | 'int' | 'boolean'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 */
	protected void emit_AttributeNodeTypeField_BooleanKeyword_1_2_or_IntKeyword_1_1_or_StringKeyword_1_0(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'abstract'?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) 'type' name=ID
	 */
	protected void emit_NodeType_AbstractKeyword_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
