/*
 * generated by Xtext 2.9.0.v201505220408
 */
package me.tomassetti.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import me.tomassetti.ui.internal.AstTransformationsDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AstTransformationsDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AstTransformationsDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AstTransformationsDslActivator.getInstance().getInjector(AstTransformationsDslActivator.ME_TOMASSETTI_ASTTRANSFORMATIONSDSL);
	}
	
}
