/*
 * generated by Xtext 2.9.0.v201505220408
 */
package me.tomassetti.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AstTransformationsDslUiModule extends me.tomassetti.ui.AbstractAstTransformationsDslUiModule {
	public AstTransformationsDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
