/**
 * generated by Xtext 2.9.0.v201505220408
 */
package me.tomassetti.scoping;

import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class AstTransformationsDslScopeProvider extends AbstractDeclarativeScopeProvider {
}
