/*
 * generated by Xtext 2.9.0.v201505220408
 */
package me.tomassetti;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AstTransformationsDslRuntimeModule extends me.tomassetti.AbstractAstTransformationsDslRuntimeModule {

}
