/*
 * generated by Xtext 2.9.0.v201505220408
 */
package me.tomassetti;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class AstTransformationsDslStandaloneSetup extends AstTransformationsDslStandaloneSetupGenerated{

	public static void doSetup() {
		new AstTransformationsDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

