/**
 * generated by Xtext 2.9.0.v201505220408
 */
package me.tomassetti.validation;

import java.io.File;
import me.tomassetti.astTransformationsDsl.AntlrGrammarRef;
import me.tomassetti.astTransformationsDsl.AstTransformationsDslPackage;
import me.tomassetti.validation.AbstractAstTransformationsDslValidator;
import org.eclipse.xtext.validation.Check;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class AstTransformationsDslValidator extends AbstractAstTransformationsDslValidator {
  public final static String UNEXISTING_FILE = "unexistingFile";
  
  @Check
  public void checkAntlrGrammarFileExist(final AntlrGrammarRef antlrGrammarRef) {
    String _grammarFile = antlrGrammarRef.getGrammarFile();
    File file = new File(_grammarFile);
    boolean _exists = file.exists();
    boolean _not = (!_exists);
    if (_not) {
      this.error("File does not exist!", AstTransformationsDslPackage.Literals.ANTLR_GRAMMAR_REF__GRAMMAR_FILE, AstTransformationsDslValidator.UNEXISTING_FILE);
    }
  }
}
