/*
 * generated by Xtext 2.9.0.v201505220408
 */
package me.tomassetti.ui.contentassist

import me.tomassetti.ui.contentassist.AbstractAstTransformationsDslProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class AstTransformationsDslProposalProvider extends AbstractAstTransformationsDslProposalProvider {
}
