/*
 * generated by Xtext 2.9.0.v201505220408
 */
package me.tomassetti;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class AstTransformationsDslUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return me.tomassetti.ui.internal.AstTransformationsDslActivator.getInstance().getInjector("me.tomassetti.AstTransformationsDsl");
	}
	
}
